homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

users_homepage:
    path:     /users
    defaults: { _controller: UsersBundle:Default:index }

users_add:
    path:     /addUser
    defaults: { _controller: UsersBundle:Default:add }